
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew binutils
brew boost
brew cairo
brew carthage
brew clisp
brew cocoapods
brew coreutils
brew docker
brew elm
brew emacs
brew fontconfig
brew freetype
brew fribidi
brew gcc
brew gdbm
brew gdk-pixbuf
brew gettext
brew gibo
brew git
brew git-secrets
brew glassfish
brew glib
brew gmp
brew gnu-sed
brew gnutls
brew gradle
brew graphite2
brew grep
brew harfbuzz
brew hub
brew icu4c
brew imagemagick@6
brew isl
brew jpeg
brew jq
brew libcroco
brew libevent
brew libffi
brew libiconv
brew libidn2
brew libmpc
brew libpng
brew librsvg
brew libsigsegv
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew little-cms2
brew lzo
brew markdown
brew mas
brew maven
brew mpfr
brew mycli
brew mysql
brew nasm
brew ncurses
brew nettle
brew node
brew oniguruma
brew openjpeg
brew openssl
brew openssl@1.1
brew p11-kit
brew pango
brew pcre
brew pcre2
brew peco
brew pixman
brew pkg-config
brew postgresql
brew pyenv
brew python
brew rbenv
brew readline
brew reattach-to-user-namespace
brew rmtrash
brew ruby-build
brew sbt
brew scala
brew sl
brew source-highlight
brew sqlite
brew tmux
brew tomcat
brew tree
brew unbound
brew webp
brew wget
brew xz
brew zsh

tap homebrew/bundle

tap homebrew/services

tap homebrew/cask
cask alfred
cask appcode
cask docker
cask intellij-idea
cask mysqlworkbench
cask figma
cask iterm2
cask slack

tap argon/mas

tap caskroom/cask
cask emacs

tap d12frosted/emacs-plus
brew emacs-plus

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 441258766 Magnet (2.4.4)
appstore 1429033973 RunCat (4.7.1)
